export const externalToolPricing: Record<string, string> = {
	'goto-connect': 'Not listed',
	hubspot: 'Not listed',
	helium10: '$96.80 / month',
	myamztools: '$32.00 / month',
	'chatgpt-plus': '$20 / month',
	jira: '$9 / user / month',
	nordpass: '$18 / month',
	freepik: '$12.20 / month',
	creatify: '$40 / month',
	'adobe-creative-cloud': '$43.20 / month',
	canva: '$4.30 / month',
	'hafiz-seo-tools': '$9.90 / month',
	capcut: '$4.50 / month',
	make: '$11.30 / month',
	semrush: '$99.00 / month',
	instantly: '$97.00 / month',
	inboxes: '$45.00 / month',
	quickbooks: 'Not listed',
	'google-workspace': 'Not listed',
};
